### PR TITLE
Made the fit.py script create the necessary directories for file output if they don't yet exist

### PR DESCRIPTION
**Pull request by Jonastjep**

### CODE REVIEW

**Review by cpawley — COMMENTED** [review]
can you also add sys.path.append('./') in line 13?

**Comment by Jonastjep** [comment]
Path appends look like this
https://github.com/jackfrost373/LHCb_Xic_production/blob/44e722c4db7fd73c6dde796da4ba9993eb748825/analysis/Scripts/MassFitting/fit.py#L13-L15

**Comment by Jonastjep** [comment]
I might actually need to change some other paths before merging, I will read the code again. This line:
https://github.com/jackfrost373/LHCb_Xic_production/blob/44e722c4db7fd73c6dde796da4ba9993eb748825/analysis/Scripts/MassFitting/fit.py#L15
is not used anymore because it relies on the dictionaries being in the origin directory

**Comment by Jonastjep** [comment]
Ok I think everything is fixed for fit.py and ready to be merged

**Review by cpawley — APPROVED** [review]

**Pull request merged**
